# Generated by Django 4.0.5 on 2022-08-17 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_title_alter_event_event_type_alter_event_tasks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tasks',
        ),
    ]
