# Generated by Django 4.0.5 on 2022-08-17 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_task2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task2',
        ),
    ]
