# Generated by Django 4.0 on 2022-10-25 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_event_user_remove_task_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combined',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modified', models.DateField(auto_now=True, verbose_name='Data de atualização')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('combination_title', models.CharField(max_length=100, null=True, verbose_name='Título do Combinado')),
                ('combination_category', models.CharField(choices=[('1', 'ATIVIDADES'), ('2', 'DOAÇÕES')], max_length=100, null=True, verbose_name='Categoria de evento')),
                ('combination_description', models.TextField(null=True, verbose_name='Descrição do Combinado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.RemoveField(
            model_name='task',
            name='event',
        ),
        migrations.AddField(
            model_name='task',
            name='task_description',
            field=models.TextField(null=True, verbose_name='Descrição da tarefa'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AddField(
            model_name='task',
            name='combination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.combined'),
        ),
    ]
